# Generated by Django 3.2.7 on 2021-09-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstitle', models.CharField(max_length=100)),
                ('newscon', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'newstable',
            },
        ),
    ]
