# Generated by Django 3.2.7 on 2021-09-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xingming', models.CharField(max_length=8)),
                ('xuehao', models.CharField(max_length=4, unique=True)),
                ('dianhua', models.CharField(max_length=11)),
                ('mima', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=4)),
                ('jianjie', models.CharField(max_length=100)),
                ('src', models.FileField(upload_to='images')),
            ],
            options={
                'db_table': 'entertable',
            },
        ),
    ]
