# Generated by Django 3.2.7 on 2021-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210912_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='enteriModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xingming', models.CharField(max_length=8)),
                ('xuehao', models.CharField(max_length=4, unique=True)),
                ('dianhua', models.CharField(max_length=11)),
                ('mima', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=4)),
                ('jianjie', models.CharField(max_length=100)),
                ('src', models.FileField(upload_to='images')),
            ],
            options={
                'db_table': 'enteritable',
            },
        ),
    ]
